publish_to: none
name: generator
description: Frontend for yakov.codes
version: 1.0.0

executables:
  generator: generator

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  pure: ^0.2.0
  intl: ^0.19.0
  reify: ^1.0.0
  web_reify: ^1.0.0
  brackets: ^1.0.0
  cord: ^0.1.0
  stream_transform: ^2.1.0
  highlight: ^0.7.0
  glob: ^2.1.2
  path: ^1.9.0
  markdown: ^7.2.1

dev_dependencies:
  lints: ^3.0.0
